


app.mongodb.url=mongodb+srv://lucianobarili:Langchain2025%21@cluster0.yyie8oe.mongodb.net/chatbot_db?retryWrites=true&w=majority&appName=Cluster0
app.mongodb.db-name=chatbot_db
app.openai.apiKey=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

app.load-articles=true
